spring:
  devtools:
    restart.enabled: true
    remote.restart.enabled: true


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootDB
    username: root
    password: '!Korea8080'

  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  thymeleaf:
    prefix: classpath:html/
    suffix: .html
    mode: HTML5
    template-resolver-order: 0

  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-location: classpath:static/


logging:
  config: classpath:logback-local.xml
  level:
    com.ppuni.todo: debug
    org.springframework: debug
